//
// Created by demongo on 11.05.2021.
//

#ifndef TIN_TORRENTLIKEP2P_SUPERVISORWORKER_H
#define TIN_TORRENTLIKEP2P_SUPERVISORWORKER_H


class SupervisorWorker {

};


#endif //TIN_TORRENTLIKEP2P_SUPERVISORWORKER_H
